# Disable the default guest user for security
loopback_users.guest = false
prometheus.tcp.port = 15692

# rabbitmq.conf

# Set the default queue type to quorum
default_queue_type = quorum

# Quorum queue replica count (adjust for redundancy)
#quorum_queue.replica_count = 3

# Queue master locator strategy to spread load across nodes
queue_master_locator = min-masters

# Overflow strategy: reject new messages when the queue is full
#overflow = reject-publish

vm_memory_high_watermark.absolute = 1GB

# Load definitions from definitions.json
management.load_definitions = /etc/rabbitmq/definitions.json

# Network Configuration
listeners.tcp.default = 5672
management.listener.port = 15672
management.listener.ip   = 0.0.0.0

# Clustering Configuration
cluster_formation.peer_discovery_backend  = classic_config
cluster_formation.classic_config.nodes.1  = rabbit@rabbitmq1
cluster_formation.classic_config.nodes.2  = rabbit@rabbitmq2
cluster_formation.classic_config.nodes.3  = rabbit@rabbitmq3

# Logging Configuration
log.dir = /var/log/rabbitmq
log.file = rabbit@${HOSTNAME}.log
log.file.level = info

# Erlang Cookie 
#Check if this belongs here
#erlang.cookie = ${RABBITMQ_ERLANG_COOKIE}