apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: Tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: Prometheus
      tracesToLogs:
        datasourceUid: Loki
        tags: ["service.name", "agentcy.pipeline_run_id", "agentcy.task_id"]
